export const ACTIONS = {
  // Navigation
  SET_SCREEN: 'SET_SCREEN',
  BACK_TO_HOME: 'BACK_TO_HOME',

  // Tournament list
  LOAD_TOURNAMENT_LIST: 'LOAD_TOURNAMENT_LIST',
  SELECT_TOURNAMENT: 'SELECT_TOURNAMENT',
  DELETE_TOURNAMENT: 'DELETE_TOURNAMENT',

  // Setup
  SET_META: 'SET_META',
  ADD_TEAM: 'ADD_TEAM',
  REMOVE_TEAM: 'REMOVE_TEAM',
  UPDATE_TEAM: 'UPDATE_TEAM',

  // Bracket
  GENERATE_BRACKET: 'GENERATE_BRACKET',
  RESHUFFLE: 'RESHUFFLE',

  // Match
  UPDATE_SCHEDULE: 'UPDATE_SCHEDULE',
  SUBMIT_RESULT: 'SUBMIT_RESULT',
  EDIT_RESULT: 'EDIT_RESULT',

  // Notices
  ADD_NOTICE: 'ADD_NOTICE',
  DELETE_NOTICE: 'DELETE_NOTICE',

  // UI
  SET_UI_ERROR: 'SET_UI_ERROR',
  TOGGLE_RESHUFFLE_CONFIRM: 'TOGGLE_RESHUFFLE_CONFIRM',

  // Reset
  RESET_BRACKET: 'RESET_BRACKET',
  RESET_ALL_TOURNAMENTS: 'RESET_ALL_TOURNAMENTS',

  // Legacy / util
  RESET_TOURNAMENT: 'RESET_TOURNAMENT',
};
